/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample.selenide.selenoid;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
